### ISSUE TITLE
Name Tag Issue

### ISSUE THREAD

**Issue by xDeathy** [UpcraftLP/Orderly#10]
Whenever I Put An Name Tag on an entity it shows a long Name which is in fact the codes such like : **textComponet{text=**.....etc 
I Hope It Gets Fixed Soon !
Here is a pic to show you what i mean !
[https://imgur.com/Cd0otzJ](url)

**Comment by luke-bravenboer** [comment]
You need to update, this is fixed in the latest version (1.1.0).

Duplicate of #4
