### ISSUE TITLE
Crash on opening game

### ISSUE THREAD

**Issue by MerryPlace** [UpcraftLP/Orderly#12]
I don't have any problem with any of my other mods. I've identified this mod to be the culprit as when I launch the game with only this mod I still crash but have no problems with the others.

**Here is the crash report:**
[crash-2019-08-21_01.32.21-client.txt](https://github.com/UpcraftLP/Orderly/files/3523694/crash-2019-08-21_01.32.21-client.txt)

**Comment by ghost** [comment]
You need to change the text in the config file to,
{
"draw": true,
"max_distance": 24,
"render_in_f1": false,
"height_above": 0.6,
"draw_background": true,
"background_padding": 2,
"background_height": 6,
"bar_height": 4,
"plate_size": 25,
"plate_size_boss": 80,
"show_attributes": true,
"show_armor": true,
"group_armor": true,
"color_by_type": false,
"hp_text_height": 14,
"show_max_h_p": true,
"show_current_h_p": true,
"show_percentage": true,
"show_on_players": true,
"show_on_bosses": true,
"show_only_focused": false,
"enable_debug_info": true,
"blacklist": [
"minecraft:shulker",
"minecraft:armor_stand",
"minecraft:cod",
"minecraft:salmon",
"minecraft:pufferfish",
"minecraft:tropical_fish",
]
}

This also is related to https://github.com/UpcraftLP/Orderly/issues/11. Hopefully we get a fix soon.

**Comment by UpcraftLP** [comment]
@NoahOrtega install Fabric API.

**Comment by UpcraftLP** [comment]
added a dependency on fabric keybindings so that it gives a proper error message in the future. see https://github.com/UpcraftLP/Orderly/commit/08b6fe17b1ed02ad353829c562351547b59b8ed1
