### ISSUE TITLE
Maxhealth shows wrong when the entity's maxhealth is greater than 1024

### ISSUE THREAD

**Issue by bluesadi** [UpcraftLP/Orderly#13]
When the entity's maxhealth is greater than 1024,no matter what the maxhealth is,the bar will show 1024

**Comment by UpcraftLP** [comment]
got any examples so I can test?

**Comment by bluesadi** [comment]
I use MythicMob（a plugin）to create a mob whose maxhealth is 3000,but the bar shows that the mob's health and maxhealth is both 1024 when the mob's current health is greater than 1024.When the mobs'health is lower than 1024,the health shows correctly,but the maxhealth shows still 1024

**Comment by bluesadi** [comment]
here
![example](https://mcbbs-bluesadi-1253334596.cos.ap-shanghai.myqcloud.com/sss.png)
actually the mob's maxhealth is 3000

**Comment by UpcraftLP** [comment]
hm.. no idea what could cause this, unless the plugin was sending wrong values to the client to make it not freak out because hte mob has too much health.

would be helpful if you could reproduce this in a singleplayer world, to make sure it's not the plugin acting weird.

**Comment by bluesadi** [comment]
I guess it's because the getHealth method in mcp works wrong...
