### ISSUE TITLE
Glitchy when used with Optifine Shaders

### ISSUE THREAD

**Issue by eclair4151** [UpcraftLP/Orderly#2]
When Optifine, and Optifabric are installed it makes the health bars glitch out

https://photos.app.goo.gl/Dt6Mpfg7yebSAEXUA

**Comment by jakewtaylor** [comment]
I get a crash when trying to use this mod with the same setup. Game launches and menus work fine, as soon as you try to load in a world it crashes, [report here](https://gist.github.com/jakewtaylor/bbe945df089dff67244b6088072bdaf3).

**Comment by TheAifam5** [comment]
Just for info, was working for a while with shaders and so, but after upgrading all mods, looks like this now.

## NO SHADERS
![MINECRAFT - NO SHADERS](https://user-images.githubusercontent.com/2192274/63192489-82ccbc00-c06b-11e9-9ae9-0487947e2dc0.png)

## WITH SHADERS
![MINECRAFT - WITH SHADERS](https://user-images.githubusercontent.com/2192274/63192490-83fde900-c06b-11e9-815e-fcc0f18f4593.png)

## VIEW ANGLE WITH SHADERS
![MINECRAFT - ROTATION 1](https://user-images.githubusercontent.com/2192274/63192599-c0c9e000-c06b-11e9-8ec2-867b7692226d.png)

![MINECRAFT - ROTATION 2](https://user-images.githubusercontent.com/2192274/63192876-641af500-c06c-11e9-87dc-1ed46cfaf1c2.png)
![MINECRAFT - ROTATION 3](https://user-images.githubusercontent.com/2192274/63192890-6c733000-c06c-11e9-9f2f-76e3e37d34ea.png)

Maybe that can help too.

Mod list:
```
Adorn-1.3.0+1.14.4.jar
appleskin-mc1.14-fabric-1.0.7.jar
aquarius-1.3.1+1.14.1.jar
clothesline-1.12.2-0.0.3.0-bundle.jar
cosmetic-armor-slots-1.1.5.jar
cotton-1.0.0-rc.3.jar
Couplings-1.1.0.jar
epicurean-gastronomy-2.2.3+1.14.2.jar
extrapieces-2.5.3.jar
fabric-api-0.3.1+build.208.jar
fabric-language-kotlin-1.3.40+build.1.jar
FirstPersonMod-1.0.1.jar
glassdoor-1.3.1.jar
glassential-fabric-1.14.4-1.1.0.jar
Hwyla-fabric-1.14.2-1.9.17-66.jar
ladderapi-1.14.4-1.1.0.jar
libblockattributes-all-0.4.9.jar
modmenu-1.7.7+build.116.jar
optifabric-0.5.1.jar
OptiFine_1.14.4_HD_U_F3_MOD.jar
orderly-1.1.0+build.13.jar
RebornCore-1.12.2-3.16.0.469-universal.jar
RoughlyEnoughItems-2.9.8+build.149.jar
sit-1.14.4-v1.1.3.jar
smokeextender-1.2.1.jar
structure_utils-2.0.0.jar
tdnf-1.5.57+1.14.4.jar
TechReborn-1.12.2-2.24.1.1017-universal.jar
terrestria-1.0.9+build.23.jar
toolbuilder-1.7.0.jar
```

**Comment by AsheX1** [comment]
just so you know using shaders are very bugged wen using this mod

once in game using shaders is gone work but health bars are gone glitch out
join/loading server/world wen shaders are on = crash
disable shaders then load/join server then load shaders

this mod is not very friendly wen playing whit shaders

crash is only gone happen wen using shaders other mods don't crash this mod
so its 
1 fabric
2 optifabric
3 optifine
4 Orderly
5 or shaders in general

**Comment by AsheX1** [comment]
retest on last build 
orderly-1.1.2+build.19

same result https://pastebin.com/ts1tkDBN
don't think there is gone be a fix for this one just unload your shaders then join a server or load a world then enable shaders once ingame
add a BUG label to this tread

also same tread combine these 2 or close 1 
Duplicate of #3
