### ISSUE TITLE
Strange icon being displayed at the position of attributes

### ISSUE THREAD

**Issue by Nyanxikun** [UpcraftLP/Orderly#35]
![2020-08-31_20 07 00](https://user-images.githubusercontent.com/58617927/91780438-9a6ada00-ebc5-11ea-9599-0069f53df12f.png)
Resourcepacks: Unity, Unity Dark, Invisible Armor
Shader: BSL v7.2
Mods: Diggus Maximus, Giselbasers Durability Viewer, Hwyla, Inventory Profiles, Mod Menu, Ok Zoomer, Optifabric, Vanilla Hammers, VoxelMap, WorldEdit, and Orderly.
Game Version is 1.16.2

**Comment by UpcraftLP** [comment]
Hm.. that's a missing texture icon.. could you try disabling optifine and/or your resourcepacks?

**Comment by Nyanxikun** [comment]
> Hm.. that's a missing texture icon.. could you try disabling optifine and/or your resourcepacks?

Hi, I tried disabling my resource pack, and it turned out the Unity resource pack caused the problem. Is there any possible way to fix this besides disabling the resource pack?

**Comment by UpcraftLP** [comment]
Well you could try to fix the resource pack?

Either way, closing this issue since it's clearly the resource pack's fault then.
