### ISSUE TITLE
Problems on 1.16.3

### ISSUE THREAD

**Issue by mikhaelcool7** [UpcraftLP/Orderly#36]
- Bars flicker while moving
- Shows Soul Sand rather than the proper loot drop on top of the health bar

**Comment by Gqblin** [comment]
same problem :(

**Comment by NightOps007** [comment]
Ditto.

**Comment by oliwoli** [comment]
This is how it looks on 1.16.5 for me

![2021-05-04_12 43 01](https://user-images.githubusercontent.com/6254817/116992459-542ac500-acd6-11eb-822d-2fef5f7fcd33.png)
![2021-05-04_12 43 20](https://user-images.githubusercontent.com/6254817/116992461-54c35b80-acd6-11eb-89a4-67585037bd1a.png)
