### ISSUE TITLE
Duplicates villager tracking with carpet mod

### ISSUE THREAD

**Issue by NightOps007** [UpcraftLP/Orderly#37]
When using /track villager iron_golem_spawning from carpet mod, it causes the tracking stuff to appear on your unit frames as well. Does that appear on purpose? Is the code for these frames forked from the same origin? Not a big issue because there is a config option that lets me move it up a little, so they no longer overlap. But the occupation info is replaced by the tracking data, this is not so good.
![image](https://i.imgur.com/8l3dqSA.png)

Just to clarify, both orderly and carpet are installed on the left of the pic. Just turned tracking on for second/third pics.
Added to carpet issues as well: [Link](https://github.com/gnembon/fabric-carpet/issues/521)

**Comment by UpcraftLP** [comment]
as explained [here](https://github.com/gnembon/fabric-carpet/issues/521#issuecomment-719491852 "gnembon/fabric-carpet#521"), this is due to the carpet mod changing the entity's name. There's nothing I can do about that.
