### ISSUE TITLE
Unnecessary modmenu:clientsideOnly

### ISSUE THREAD

**Issue by K0-RR** [UpcraftLP/Orderly#38]
[main/INFO]: Mod 'orderly' uses the modmenu:clientsideOnly custom value unnecessarily, as it can be inferred from the mod's declared environment.
I know this doesn't affect gameplay but it's just spamming in the console.

**Comment by UpcraftLP** [comment]
Blame ModMenu for logging it to INFO rather than DEBUG.
it'll be gone with the next update.
