### ISSUE TITLE
Info on updates?

### ISSUE THREAD

**Issue by Skaytacium** [UpcraftLP/Orderly#39]
Great port, but there are a few issues.

## System info

Mod version: orderly-2.0.0-alpha.10+custom-1.16
MC version: 1.16.5
OS: Windows 10 19042
Fabric Loader version: 0.11.2
Fabric API version: 0.31.0
Other mods used (might be incompatible):
- MiniHUD
- Sodium
- Phosphor
- Litematica

Note: Jar was obtained from compiling from source, didn't download it from releases.

## Issues

- Quite a bit of flickering
- Sometimes it just leaves the health blank, no values

## What I tried doing

- Updating fabric API
- Updating the fabric loader
- `gradlew.bat test`

## Conclusion

Not really a major bug probably, I would love to open a PR, but I'm not a Java developer.
Plus the port is still in alpha, maybe a final stable release is due? Or maybe it's just mod incompatibility.
Also, any info on new commits or updates would be great.

Thanks,
Sid

**Comment by UpcraftLP** [comment]
Hello, yes I had planned on publishing further updates, but other work got in the way.

As for the issues you described: could you try to reproduce them without sodium?

**Comment by K0-RR** [comment]
I have the same issues (flickering) and I use Sodium
![image](https://user-images.githubusercontent.com/43277609/110630928-4c531680-81a6-11eb-84a8-d18cc0ca6db5.png)
Note: display max health is enabled, it just disappears in some directions.

**Comment by K0-RR** [comment]
I only moved the cursor a little bit.
![image](https://user-images.githubusercontent.com/43277609/110631248-9b00b080-81a6-11eb-8004-4b65d85ec451.png)

**Comment by K0-RR** [comment]
It does happen without Sodium, I recommend renaming the issue. _Edit because I'm bad at reading._

**Comment by Skaytacium** [comment]
Yeah, happens without sodium as previously mentioned. The issue name is fine as I just generally wanted to mainly ask if there are going to be any updates to fix the aforementioned problem.

Anyway, I'm closing this as my question has been answered,

Thanks,
Sid
