### ISSUE TITLE
Name tagged entities aren't handled properly

### ISSUE THREAD

**Issue by hugeblank** [UpcraftLP/Orderly#4]
Leading to them looking like absolute units:
![image](https://user-images.githubusercontent.com/16393543/62825391-9fdf2780-bb5f-11e9-83c4-b159f10aa066.png)

MC: 1.14.4
Fabric: 0.4.8+build.159
Orderly: 1.0.1+build.7

**Comment by falimero** [comment]
to follow
same here ...
