### ISSUE TITLE
Water becomes fully transparent when looking at it through the bar.

### ISSUE THREAD

**Issue by K0-RR** [UpcraftLP/Orderly#40]
![image](https://user-images.githubusercontent.com/43277609/110630196-5c1e2b00-81a5-11eb-8278-e81a946abfc1.png)

Also, what is this icon on the right?

**Comment by K0-RR** [comment]
Sorry for ping.

**Comment by UpcraftLP** [comment]
huh, somehow must've missed this.

Anyway, this is a limitation with Minecraft 1.16's rendering, sadly nothing I can do about that. It will be fixed in 1.17 tho, when I get around to updating the mod.
