### ISSUE TITLE
Incompatibility with Origins

### ISSUE THREAD

**Issue by chorusstar1o1** [UpcraftLP/Orderly#42]
Incompatible with Origins: https://www.curseforge.com/minecraft/mc-mods/origins

Launching game gives the error "Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'origins'!" upon initializing.

**Comment by UpcraftLP** [comment]
could you  please provide a full crash log?

**Comment by chorusstar1o1** [comment]
[crash-2021-05-10_12.29.22-client.txt](https://github.com/UpcraftLP/Orderly/files/6453595/crash-2021-05-10_12.29.22-client.txt)

**Comment by chorusstar1o1** [comment]
<img width="404" alt="Screenshot 2021-05-10 123049" src="https://user-images.githubusercontent.com/83771812/117693018-95661d80-b18b-11eb-93d2-a94aae428e80.png">
current mods

**Comment by UpcraftLP** [comment]
install the latest version of cloth config manually, that should fix it
