### ISSUE TITLE
Health bars rendering dark green and transparent 

### ISSUE THREAD

**Issue by Stanfordia** [UpcraftLP/Orderly#43]
![unknown](https://user-images.githubusercontent.com/84988668/120023424-9b893600-bfa2-11eb-8153-855e9e309904.png)

The health bars are weirdly glitchy, can hardly see them. I was using sodium but I know that causes rendering issues so I removed that. Any other ideas?

**Comment by githubbingitup** [comment]
Same here. It happens without any other mods installed.
