### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Spookiee** [UpcraftLP/Orderly#46]
when i open the modmenu and then hit the configure button minecraft crashes and leaves me with this message

The game crashed whilst rendering screen
Error: java.lang.NoSuchMethodError: net.minecraft.class_327.method_27517(Lnet/minecraft/class_4587;Lnet/minecraft/class_5348;FFI)I
Exit Code: -1

please help, i want to configure it. thanks!

**Comment by UpcraftLP** [comment]
Could you provide a full crash log, as well as what versions of

- Orderly
- Minecraft
- and Modmenu

you were using?

**Comment by Spookiee** [comment]
i was using fabric loader 1.16.5 orderly 1.16.5 and modmenu 1.16.5, i was given this message 

The game crashed whilst rendering screen
Error: java.lang.NoSuchMethodError: net.minecraft.class_327.method_27517(Lnet/minecraft/class_4587;Lnet/minecraft/class_5348;FFI)I
Exit Code: -1

**Comment by Spookiee** [comment]
also api 1.16.5
