### ISSUE TITLE
Incorrect max health rendering

### ISSUE THREAD

**Issue by hugeblank** [UpcraftLP/Orderly#6]
Leading to them (again) looking like absolute beefcakes. This time their current health is accurate, so injured beefcakes. For comparison a correctly displayed pigman is shown. I've only seen this inaccuracy on pigman so it may be something in the game code rather than the mod. Either way it's not that big of a deal and barely worth reporting.

![2019-08-14_18 10 49](https://user-images.githubusercontent.com/16393543/63130690-2b95f100-bf70-11e9-8f1a-56c9ff5e200f.png)

MC: 1.14.4
Fabric: 0.4.8+build.159
Orderly: 1.0.1+build.7

**Comment by hugeblank** [comment]
@UpcraftLP This issue still occurs after 1.1.0:

![image](https://user-images.githubusercontent.com/16393543/63148666-c5808c80-bfb6-11e9-9365-81cec3902753.png)
I wish there was some way to show that this was in 1.1.0 but I guess you'll just have to trust me here.
Also I hit this guy a couple of times, he was at 20/83.95 before I smacked him

**Comment by UpcraftLP** [comment]
hm.. will have to look into this then

**Comment by UpcraftLP** [comment]
@hugeblank does this still occur on 1.15.2?

**Comment by hugeblank** [comment]
I know it still happens on 1.15.1, haven't had the chance to test it on .2
